version: '3.9'

services:
  notebook:
    container_name: notebook
    build:
      context: .
      target: ${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: notebook_db
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}

volumes:
  postgres-data:
